# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170807_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='timstamp',
            new_name='timestamp',
        ),
    ]
